### ISSUE TITLE
tiers

### ISSUE THREAD

**Issue by altwebS** [FantasyFootballAnalytics/ffanalytics#125]
The updated tier calculation is providing very different information compared to the soon to be deprecated set_tiers.  Is this expected?  As an example, there were only a few tier 1 per position.  Picking a random week from last season there was 2 or 3 DST that were a tier 1 and 2022 week 1 has 21 DST teams set as a tier 1.

**Comment by atungate** [comment]
Hey altwebS, it looks like it is because out CBS scrape is accidental grabbing the season-long projections (week 1 is not available yet). So, their inclusion throws-off the tiers. I am happy to get in the weeds / explain more if it is helpful. For now, drop CBS from the week 1 pull (until their Week 1 projections are up), and I'll work on a fix that makes sure the season-long projections cannot leak into the week 1 projections.

**Comment by altwebS** [comment]
Makes perfect sense. Thanks for the offer, but no need for the weeds- Makes sense from the details I was looking at last night.  I’ll validate later tonight without CBS scrape.

**Comment by altwebS** [comment]
Validated and working as mentioned.  Closing issue.
