### ISSUE TITLE
CBS scrape pulling previous weeks stats, not projections

### ISSUE THREAD

**Issue by BeardedJayhawk** [FantasyFootballAnalytics/ffanalytics#132]
`scrape_data(src = "CBS", pos = "RB", season = 2022, week = 17)`
returns actual stats from week 16, not projections for week 17.

this may be why the range has this massive ceiling for several players on the shiny app on the website, because if a player went off the week prior, it is imputed as a projected performance into the scrape.

when you go to the URL that is scraped (https://www.cbssports.com/fantasy/football/stats/RB/2022/17/projections/nonppr/), this is what you see:

![image](https://user-images.githubusercontent.com/52295129/209845523-69baf905-cf12-4705-9f3f-fc18585905fe.png)

and this is the actual stats for week 16 in yahoo:

![image](https://user-images.githubusercontent.com/52295129/209845778-238b4bdb-54ff-46fc-9b29-0ebcb5681edf.png)

**Comment by atungate** [comment]
Hey BeardedJayhawk, it looks like CBS is not putting out new projections anymore. I remember this happening last year as well. I am going to keep this open for now because I'll see if there is an easy way for the CBS scrape to throw an error (rather than scrape old stats). Thank you for raising the issue!
